#!/bin/bash

set -e

source "$(dirname "$0")/git-organize"

url="${@:$#}"

echo "[II] cloning git path $url ..."

newpath=$(repo_dest_path "$url")

if [[ -e "${newpath}" ]]; then
	echo "[EE] $newpath already exists"
	exit 1
fi

git clone "$@" "$newpath/"
